# Generated by Django 4.2.4 on 2023-09-04 13:37

import cpf_field.models
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('value', models.FloatField(help_text='Value for loan')),
                ('assess', models.BooleanField(default=False)),
                ('approved_by_api', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Loans',
            },
        ),
    ]
